# Generated by Django 5.2.7 on 2025-12-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='mmu_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
