# Generated by Django 5.2.7 on 2025-12-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_mmu_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='mmu_number',
        ),
    ]
