# Generated by Django 5.2.7 on 2025-11-10 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=200)),
                ('disease_category', models.CharField(choices=[('CD', 'Communicable Disease'), ('NCD', 'Non-Communicable Disease'), ('RCH', 'Reproductive and Child Health'), ('MA', 'Minor Ailment/Other')], max_length=50)),
                ('treatment_given', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
