# Generated by Django 5.2.7 on 2025-11-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('ECG Machine', 'ECG Machine'), ('X-Ray', 'X-Ray'), ('BP Monitor', 'BP Monitor'), ('Thermometer', 'Thermometer'), ('Other', 'Other')], max_length=50)),
                ('mmu_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional'), ('Under Maintenance', 'Under Maintenance')], default='Functional', max_length=50)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inspection_photo', models.ImageField(blank=True, null=True, upload_to='equipment_photos/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
