# Generated by Django 5.2.7 on 2025-11-10 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='calibration_due_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='inspection_photo',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='mmu_code',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='next_maintenance',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='remarks',
        ),
        migrations.AddField(
            model_name='equipment',
            name='device_type',
            field=models.CharField(default='General Equipment', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inspection_image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_inspections/'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_alert',
            field=models.CharField(choices=[('None', 'None'), ('Pending Maintenance', 'Pending Maintenance'), ('Pending Calibration', 'Pending Calibration'), ('Delayed Maintenance', 'Delayed Maintenance')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional'), ('Under Maintenance', 'Under Maintenance')], default='Functional', max_length=30),
        ),
    ]
