# Generated by Django 5.2.7 on 2025-11-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Medicine', 'Medicine'), ('Consumable', 'Consumable'), ('Diagnostic Kit', 'Diagnostic Kit'), ('Equipment', 'Equipment')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Low Stock', 'Low Stock'), ('Expired', 'Expired'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
