# Generated by Django 5.2.7 on 2025-11-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='inventory',
            name='restocked_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
