# Generated by Django 5.2.7 on 2025-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMUAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_no', models.IntegerField(unique=True)),
                ('mmu_number', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('base_location', models.CharField(max_length=200)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('phc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vhc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vhc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('habitation', models.CharField(blank=True, max_length=200, null=True)),
                ('lat2', models.CharField(blank=True, max_length=100, null=True)),
                ('long2', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed_day', models.CharField(blank=True, max_length=50, null=True)),
                ('week', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmu_id', models.CharField(max_length=100)),
                ('service_no', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('mandal', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('route_code', models.CharField(blank=True, max_length=50)),
                ('distance', models.CharField(blank=True, max_length=50)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mmu_id', 'date'), name='unique_mmu_per_day')],
            },
        ),
    ]
