# Generated by Django 5.2.7 on 2025-11-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_by', models.CharField(max_length=100)),
                ('mmu_id', models.CharField(max_length=50)),
                ('odometer', models.IntegerField()),
                ('equipment', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('repaired', models.CharField(default='No', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
