# Generated by Django 5.2.7 on 2025-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmaintenance',
            name='maintenance_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/'),
        ),
    ]
