# Generated by Django 5.2.7 on 2025-11-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_fieldmaintenance_maintenance_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmaintenance',
            name='maintenance_image',
        ),
    ]
