# Generated by Django 5.2.7 on 2025-11-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('test_name', models.CharField(choices=[('HB', 'Hemoglobin'), ('RBS', 'Random Blood Sugar'), ('CBC', 'Complete Blood Count'), ('URINE', 'Urine Test'), ('RDT', 'Rapid Diagnostic Test'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('sample_date', models.DateField()),
                ('result', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('result_value', models.CharField(blank=True, max_length=200, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('mmu_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sample_date', '-created_at'],
            },
        ),
    ]
