# Generated by Django 5.2.7 on 2025-11-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mmu_name', models.CharField(max_length=100)),
                ('village_name', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default='Morning', max_length=50)),
                ('total_patients', models.PositiveIntegerField(default=0)),
                ('elderly', models.PositiveIntegerField(default=0)),
                ('pregnant_women', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('chronic_cases', models.PositiveIntegerField(default=0)),
                ('palliative_cases', models.PositiveIntegerField(default=0)),
                ('anm_participation', models.BooleanField(default=False)),
                ('aww_participation', models.BooleanField(default=False)),
                ('asha_participation', models.BooleanField(default=False)),
                ('feedback_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
