# Generated by Django 5.2.7 on 2025-11-14 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camp_location', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
