# Generated by Django 5.2.7 on 2025-11-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_maintenanceform_is_repaired_maintenanceform_mmu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceform',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
