# Generated by Django 5.2.7 on 2025-11-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_maintenanceform_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceform',
            name='maintenance_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/'),
        ),
    ]
