# Generated by Django 5.2.7 on 2025-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSourceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceName', models.CharField(max_length=100)),
                ('gpsLat', models.CharField(blank=True, max_length=50, null=True)),
                ('gpsLong', models.CharField(blank=True, max_length=50, null=True)),
                ('waterType', models.CharField(max_length=100)),
                ('sampleDate', models.DateField()),
                ('chlorineLevel', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Unsafe', 'Unsafe')], max_length=20)),
                ('reportFile', models.FileField(blank=True, null=True, upload_to='water_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
